# Generated by Django 5.2.14 on 2026-06-03 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialDocumentArchive',
            fields=[
                ('document_id_PK', models.AutoField(primary_key=True, serialize=False)),
                ('related_module', models.CharField(max_length=100)),
                ('related_record_id', models.IntegerField()),
                ('document_type', models.CharField(max_length=100)),
                ('file_path', models.CharField(max_length=500)),
                ('file_hash', models.CharField(max_length=255)),
                ('verification_status', models.CharField(max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'FINANCIAL_DOCUMENT_ARCHIVE',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('member_id_PK', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('contact_number', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('employment_status', models.CharField(max_length=50)),
                ('membership_status', models.CharField(max_length=50)),
                ('member_type', models.CharField(max_length=50)),
                ('date_joined', models.DateField()),
            ],
            options={
                'db_table': 'MEMBER',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notification_id_PK', models.AutoField(primary_key=True, serialize=False)),
                ('recipient_type', models.CharField(max_length=50)),
                ('recipient_id', models.IntegerField()),
                ('recipient_name', models.CharField(max_length=255)),
                ('recipient_contact', models.CharField(blank=True, max_length=255, null=True)),
                ('notification_type', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('delivery_status', models.CharField(max_length=50)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'NOTIFICATION',
            },
        ),
        migrations.CreateModel(
            name='OfficerUser',
            fields=[
                ('user_id_PK', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=50)),
                ('account_status', models.CharField(max_length=50)),
                ('term_start', models.DateField(blank=True, null=True)),
                ('term_end', models.DateField(blank=True, null=True)),
                ('mfa_secret', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'OFFICER_USER',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('audit_id_PK', models.AutoField(primary_key=True, serialize=False)),
                ('actor_type', models.CharField(max_length=50)),
                ('actor_id', models.IntegerField()),
                ('action', models.CharField(max_length=255)),
                ('entity_type', models.CharField(max_length=100)),
                ('ip_address', models.GenericIPAddressField()),
                ('device_info', models.CharField(blank=True, max_length=255, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('entity_id', models.ForeignKey(db_column='entity_id', on_delete=django.db.models.deletion.CASCADE, to='core_system.financialdocumentarchive')),
            ],
            options={
                'db_table': 'AUDIT_LOG',
            },
        ),
        migrations.CreateModel(
            name='Claimant',
            fields=[
                ('claimant_id_PK', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('contact_number', models.CharField(blank=True, max_length=50, null=True)),
                ('relationship_to_member', models.CharField(max_length=100)),
                ('authorization_status', models.CharField(max_length=50)),
                ('member_id_FK', models.ForeignKey(db_column='member_id_FK', on_delete=django.db.models.deletion.CASCADE, to='core_system.member')),
            ],
            options={
                'db_table': 'CLAIMANT',
            },
        ),
        migrations.CreateModel(
            name='MonthlyDues',
            fields=[
                ('dues_id_PK', models.AutoField(primary_key=True, serialize=False)),
                ('month_covered', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(max_length=50)),
                ('payment_status', models.CharField(max_length=50)),
                ('receipt_number', models.CharField(blank=True, max_length=100, null=True)),
                ('deduction_batch_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('remittance_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('member_id_FK', models.ForeignKey(db_column='member_id_FK', on_delete=django.db.models.deletion.RESTRICT, to='core_system.member')),
                ('recorded_by_user_id_FK', models.ForeignKey(db_column='recorded_by_user_id_FK', on_delete=django.db.models.deletion.RESTRICT, to='core_system.officeruser')),
            ],
            options={
                'db_table': 'MONTHLY_DUES',
            },
        ),
        migrations.CreateModel(
            name='MembershipFee',
            fields=[
                ('fee_id_PK', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateField()),
                ('payment_status', models.CharField(max_length=50)),
                ('receipt_number', models.CharField(blank=True, max_length=100, null=True)),
                ('deposit_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('member_id_FK', models.ForeignKey(db_column='member_id_FK', on_delete=django.db.models.deletion.RESTRICT, to='core_system.member')),
                ('recorded_by_user_id_FK', models.ForeignKey(db_column='recorded_by_user_id_FK', on_delete=django.db.models.deletion.RESTRICT, to='core_system.officeruser')),
            ],
            options={
                'db_table': 'MEMBERSHIP_FEE',
            },
        ),
        migrations.CreateModel(
            name='MedicalAid',
            fields=[
                ('medical_aid_id_PK', models.AutoField(primary_key=True, serialize=False)),
                ('request_date', models.DateField()),
                ('hospital_bill_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('claim_year', models.IntegerField()),
                ('document_status', models.CharField(max_length=50)),
                ('policy_record_status', models.CharField(max_length=50)),
                ('validated_aid_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(max_length=50)),
                ('president_decision', models.CharField(blank=True, max_length=50, null=True)),
                ('release_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('acknowledgement_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('member_id_FK', models.ForeignKey(db_column='member_id_FK', on_delete=django.db.models.deletion.RESTRICT, to='core_system.member')),
                ('auditor_verified_by_user_id_FK', models.ForeignKey(blank=True, db_column='auditor_verified_by_user_id_FK', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_aid_auditor_verified', to='core_system.officeruser')),
                ('president_decided_by_user_id_FK', models.ForeignKey(blank=True, db_column='president_decided_by_user_id_FK', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='death_aid_president_decided', to='core_system.officeruser')),
                ('released_by_user_id_FK', models.ForeignKey(blank=True, db_column='released_by_user_id_FK', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='death_aid_released', to='core_system.officeruser')),
                ('treasurer_validated_by_user_id_FK', models.ForeignKey(blank=True, db_column='treasurer_validated_by_user_id_FK', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='death_aid_treasurer_validated', to='core_system.officeruser')),
            ],
            options={
                'db_table': 'MEDICAL_AID',
            },
        ),
        migrations.CreateModel(
            name='LoginAttemptLog',
            fields=[
                ('attempt_id_PK', models.AutoField(primary_key=True, serialize=False)),
                ('username_used', models.CharField(max_length=150)),
                ('ip_address', models.GenericIPAddressField()),
                ('device_info', models.CharField(blank=True, max_length=255, null=True)),
                ('result', models.CharField(max_length=50)),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('user_id_FK', models.ForeignKey(blank=True, db_column='user_id_FK', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core_system.officeruser')),
            ],
            options={
                'db_table': 'LOGIN_ATTEMPT_LOG',
            },
        ),
        migrations.AddField(
            model_name='financialdocumentarchive',
            name='uploaded_by_user_id_FK',
            field=models.ForeignKey(db_column='uploaded_by_user_id_FK', on_delete=django.db.models.deletion.RESTRICT, to='core_system.officeruser'),
        ),
        migrations.CreateModel(
            name='DeathAid',
            fields=[
                ('death_aid_id_PK', models.AutoField(primary_key=True, serialize=False)),
                ('claim_date', models.DateField()),
                ('claim_type', models.CharField(max_length=50)),
                ('deceased_name', models.CharField(max_length=255)),
                ('relationship_to_member', models.CharField(max_length=100)),
                ('benefit_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('document_status', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('president_decision', models.CharField(blank=True, max_length=50, null=True)),
                ('release_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('acknowledgement_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('claimant_id_FK', models.ForeignKey(db_column='claimant_id_FK', on_delete=django.db.models.deletion.RESTRICT, to='core_system.claimant')),
                ('member_id_FK', models.ForeignKey(db_column='member_id_FK', on_delete=django.db.models.deletion.RESTRICT, to='core_system.member')),
                ('auditor_verified_by_user_id_FK', models.ForeignKey(blank=True, db_column='auditor_verified_by_user_id_FK', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='death_aid_auditor_verified', to='core_system.officeruser')),
                ('president_decided_by_user_id_FK', models.ForeignKey(blank=True, db_column='president_decided_by_user_id_FK', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_aid_president_decided', to='core_system.officeruser')),
                ('released_by_user_id_FK', models.ForeignKey(blank=True, db_column='released_by_user_id_FK', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_aid_released', to='core_system.officeruser')),
                ('treasurer_validated_by_user_id_FK', models.ForeignKey(blank=True, db_column='treasurer_validated_by_user_id_FK', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core_system.officeruser')),
            ],
            options={
                'db_table': 'DEATH_AID',
            },
        ),
        migrations.CreateModel(
            name='AuditFindingsReport',
            fields=[
                ('audit_report_id_PK', models.AutoField(primary_key=True, serialize=False)),
                ('report_title', models.CharField(max_length=255)),
                ('report_period', models.CharField(max_length=100)),
                ('findings_summary', models.TextField()),
                ('report_status', models.CharField(max_length=50)),
                ('prepared_date', models.DateField()),
                ('board_submission_date', models.DateField(blank=True, null=True)),
                ('board_meeting_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('presentation_status', models.CharField(max_length=50)),
                ('certification_status', models.CharField(max_length=50)),
                ('certified_by_user_id_FK', models.ForeignKey(blank=True, db_column='certified_by_user_id_FK', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_reports_certified', to='core_system.officeruser')),
                ('prepared_by_user_id_FK', models.ForeignKey(db_column='prepared_by_user_id_FK', on_delete=django.db.models.deletion.RESTRICT, related_name='audit_reports_prepared', to='core_system.officeruser')),
            ],
            options={
                'db_table': 'AUDIT_FINDINGS_REPORT',
            },
        ),
        migrations.CreateModel(
            name='AccessSession',
            fields=[
                ('session_id_PK', models.AutoField(primary_key=True, serialize=False)),
                ('token_id', models.CharField(max_length=255, unique=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('device_info', models.CharField(blank=True, max_length=255, null=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('session_status', models.CharField(max_length=50)),
                ('user_id_FK', models.ForeignKey(db_column='user_id_FK', on_delete=django.db.models.deletion.CASCADE, to='core_system.officeruser')),
            ],
            options={
                'db_table': 'ACCESS_SESSION',
            },
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name='SensitiveReadLog',
                    fields=[
                        ('read_id_PK', models.AutoField(primary_key=True, serialize=False)),
                        ('module', models.CharField(max_length=100)),
                        ('record_id', models.IntegerField()),
                        ('purpose', models.CharField(max_length=255)),
                        ('timestamp', models.DateTimeField(auto_now_add=True)),
                        ('user_id_FK', models.ForeignKey(db_column='user_id_FK', on_delete=django.db.models.deletion.CASCADE, to='core_system.officeruser')),
                    ],
                    options={
                        'db_table': 'SENSITIVE_READ_LOG',
                    },
                ),
            ],
        ),
    ]
