# Generated by Django 5.2.14 on 2026-06-03 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditfindingsreport',
            name='prepared_by_user_id_FK',
            field=models.ForeignKey(db_column='prepared_by_user_id_FK', on_delete=django.db.models.deletion.RESTRICT, related_name='audit_findings_reports_prepared', to='core_system.officeruser'),
        ),
    ]
