# Generated by Django 5.2.5 on 2026-06-12 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_system', '0002_alter_auditfindingsreport_prepared_by_user_id_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlydues',
            name='payment_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
