# Generated by Django 5.2.5 on 2026-06-12 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_system', '0003_monthlydues_payment_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionVerification',
            fields=[
                ('verification_id', models.AutoField(primary_key=True, serialize=False)),
                ('table_name', models.CharField(max_length=50)),
                ('record_id', models.IntegerField()),
                ('verification_status', models.CharField(default='Pending Verification', max_length=50)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('auditor_id_FK', models.ForeignKey(blank=True, db_column='auditor_id_FK', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_verifications_audited', to='core_system.officeruser')),
                ('president_id_FK', models.ForeignKey(blank=True, db_column='president_id_FK', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_verifications_approved', to='core_system.officeruser')),
            ],
            options={
                'db_table': 'transaction_verification',
            },
        ),
    ]
