# Generated by Django 5.2.5 on 2026-06-13 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_system', '0004_transactionverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalaid',
            name='requested_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
