# Generated by Django 5.2.5 on 2026-06-13 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_system', '0005_medicalaid_requested_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalaid',
            name='hospital_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
