# Generated by Django 5.2.5 on 2026-06-15 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_system', '0006_medicalaid_hospital_name'),
    ]

    from django.db import migrations, models

    def delete_duplicate_membership_fees(apps, schema_editor):
        MembershipFee = apps.get_model('core_system', 'MembershipFee')
        from django.db.models import Count
        duplicates = (
            MembershipFee.objects
            .values('member_id_FK', 'receipt_number')
            .annotate(count=Count('fee_id_PK'))
            .filter(count__gt=1)
        )
        for dup in duplicates:
            fees = MembershipFee.objects.filter(member_id_FK=dup['member_id_FK'], receipt_number=dup['receipt_number']).order_by('fee_id_PK')
                        # Keep the earliest (smallest fee_id_PK), delete the rest
            first_fee = fees.first()
            if first_fee:
                ids_to_delete = fees.exclude(pk=first_fee.pk).values_list('pk', flat=True)
                MembershipFee.objects.filter(pk__in=ids_to_delete).delete()

    operations = [
        migrations.RunPython(delete_duplicate_membership_fees, reverse_code=migrations.RunPython.noop),
        migrations.AlterUniqueTogether(
            name='membershipfee',
            unique_together={('member_id_FK', 'receipt_number')},
        ),
    ]
