# Generated by Django 5.2.5 on 2026-06-16 03:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core_system', '0008_merge'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportingProof',
            fields=[
                ('proof_id_PK', models.AutoField(primary_key=True, serialize=False)),
                ('object_id', models.PositiveIntegerField(db_column='object_id')),
                ('file', models.FileField(db_column='file_path', max_length=500, upload_to='supporting_proofs/%Y/%m/%d/')),
                ('file_name', models.CharField(db_column='file_name', max_length=255)),
                ('file_type', models.CharField(db_column='file_type', max_length=100)),
                ('file_sha256', models.CharField(db_column='file_sha256', max_length=64)),
                ('row_signature', models.CharField(db_column='row_signature', max_length=64)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, db_column='uploaded_at')),
                ('content_type', models.ForeignKey(db_column='content_type_id', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('uploaded_by', models.ForeignKey(db_column='uploaded_by_user_id_FK', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supporting_proofs', to='core_system.officeruser')),
            ],
            options={
                'db_table': 'SUPPORTING_PROOF',
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='SUPPORTING__content_09c351_idx'), models.Index(fields=['uploaded_at'], name='SUPPORTING__uploade_b01f8c_idx')],
            },
        ),
    ]
