# Generated by Django 5.2.5 on 2026-06-16 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core_system', '0009_supportingproof'),
    ]

    operations = [
        migrations.CreateModel(
            name='RevisionLog',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('object_id', models.PositiveIntegerField(db_column='object_id')),
                ('rejection_reason', models.TextField()),
                ('snapshot_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('auditor_id_FK', models.ForeignKey(db_column='auditor_id_FK', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core_system.officeruser')),
                ('content_type', models.ForeignKey(db_column='content_type_id', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'db_table': 'revision_log',
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='revision_lo_content_6da5e6_idx'), models.Index(fields=['created_at'], name='revision_lo_created_91651d_idx')],
            },
        ),
    ]
