# Generated by Django 5.2.5 on 2026-06-18 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_system', '0010_revision_log_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='employee_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='position',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='member_type',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
