# Generated by Django 5.2.5 on 2026-06-18 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_system', '0011_member_department_member_employee_id_member_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipfee',
            name='month_covered',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
