# Generated by Django 5.2.5 on 2026-06-18 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_system", "0012_membershipfee_month_covered"),
    ]

    operations = [
        migrations.AddField(
            model_name="membershipfee",
            name="payment_method",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.RunSQL(
            sql=[
                "UPDATE MEMBERSHIP_FEE "
                "SET payment_method = payment_status, payment_status = 'Full Payment' "
                "WHERE payment_status = 'Over-the-Counter Cash'",
                "UPDATE MEMBERSHIP_FEE "
                "SET payment_status = 'Full Payment' "
                "WHERE payment_status NOT IN ('Full Payment', 'Partial')",
            ],
            reverse_sql=[
                "UPDATE MEMBERSHIP_FEE "
                "SET payment_status = payment_method "
                "WHERE payment_method = 'Over-the-Counter Cash'",
            ],
        ),
        migrations.AlterField(
            model_name="membershipfee",
            name="payment_method",
            field=models.CharField(max_length=50),
        ),
    ]
