# Generated by Django 5.2.14 on 2026-06-21 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_system', '0013_membershipfee_payment_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditorPaymentVerification',
            fields=[
                ('auditor_payment_id_PK', models.AutoField(primary_key=True, serialize=False)),
                ('target_table', models.CharField(max_length=50)),
                ('target_record_id', models.IntegerField()),
                ('verified_at', models.DateTimeField()),
                ('result_status', models.CharField(max_length=50)),
                ('auditor_remarks', models.TextField()),
                ('evidence_file_path', models.CharField(blank=True, max_length=500, null=True)),
                ('evidence_file_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('auditor_id_FK', models.ForeignKey(db_column='auditor_id_FK', on_delete=django.db.models.deletion.RESTRICT, to='core_system.officeruser')),
            ],
            options={
                'db_table': 'AUDITOR_PAYMENT_VERIFICATION',
                'constraints': [models.UniqueConstraint(fields=('target_table', 'target_record_id'), name='uq_auditor_payment_verif_target')],
            },
        ),
    ]
