# Generated by Django 5.2.5 on 2026-06-21 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_system', '0015_audit_aid_verification_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditoraidverification',
            name='auditor_aid_verification_id_PK',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
