# Generated by Django 5.2.5 on 2026-06-29 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_system', '0016_alter_auditoraidverification_auditor_aid_verification_id_pk'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionArchive',
            fields=[
                ('archive_id_PK', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(max_length=50)),
                ('record_id', models.IntegerField()),
                ('member_name', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('validated_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(max_length=50)),
                ('payment_method', models.CharField(blank=True, max_length=50, null=True)),
                ('release_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
                ('archived_by_user_id_FK', models.ForeignKey(blank=True, db_column='archived_by_user_id_FK', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_transactions', to='core_system.officeruser')),
                ('member_id_FK', models.ForeignKey(blank=True, db_column='member_id_FK', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core_system.member')),
                ('released_by_user_id_FK', models.ForeignKey(blank=True, db_column='released_by_user_id_FK', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_releases', to='core_system.officeruser')),
            ],
            options={
                'db_table': 'transaction_archive',
                'indexes': [models.Index(fields=['transaction_type', 'record_id'], name='transaction_transac_4a6ac9_idx'), models.Index(fields=['status'], name='transaction_status_abeab9_idx')],
            },
        ),
    ]
