# Generated by Django 5.2.5 on 2026-06-29 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_system', '0017_transactionarchive'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalAuditTrail',
            fields=[
                ('trail_id', models.AutoField(primary_key=True, serialize=False)),
                ('table_name', models.CharField(max_length=100)),
                ('record_id', models.IntegerField()),
                ('action', models.CharField(max_length=20)),
                ('old_values', models.JSONField(blank=True, null=True)),
                ('new_values', models.JSONField(blank=True, null=True)),
                ('actor_type', models.CharField(max_length=50)),
                ('actor_id', models.IntegerField(blank=True, null=True)),
                ('actor_name', models.CharField(max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('device_info', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'GLOBAL_AUDIT_TRAIL',
                'indexes': [models.Index(fields=['table_name', 'record_id', 'timestamp'], name='GLOBAL_AUDI_table_n_f2953e_idx')],
            },
        ),
    ]
