# Generated by Django 5.2.14 on 2026-06-30 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_system', '0018_add_global_audit_trail'),
    ]

    operations = [
        migrations.CreateModel(
            name='AidTrackingPost',
            fields=[
                ('post_id_PK', models.AutoField(primary_key=True, serialize=False)),
                ('aid_type', models.CharField(max_length=50)),
                ('target_month', models.CharField(max_length=7)),
                ('total_expected', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_collected', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archive_id_FK', models.ForeignKey(db_column='archive_id_FK', on_delete=django.db.models.deletion.CASCADE, related_name='aid_tracking_posts', to='core_system.transactionarchive')),
                ('created_by_user_id_FK', models.ForeignKey(db_column='created_by_user_id_FK', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aid_posts_created', to='core_system.officeruser')),
            ],
            options={
                'db_table': 'AID_TRACKING_POST',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('contribution_id_PK', models.AutoField(primary_key=True, serialize=False)),
                ('expected_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='NOT_PAID', max_length=20)),
                ('is_manually_overridden', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aid_tracking_post_id_FK', models.ForeignKey(db_column='aid_tracking_post_id_FK', on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='core_system.aidtrackingpost')),
                ('member_id_FK', models.ForeignKey(db_column='member_id_FK', on_delete=django.db.models.deletion.RESTRICT, to='core_system.member')),
                ('updated_by_user_id_FK', models.ForeignKey(blank=True, db_column='updated_by_user_id_FK', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contribution_updates', to='core_system.officeruser')),
            ],
            options={
                'db_table': 'CONTRIBUTION',
                'unique_together': {('aid_tracking_post_id_FK', 'member_id_FK')},
            },
        ),
    ]
