# Generated by Django 5.2.14 on 2026-07-02 07:13

import django.db.models.deletion
from django.db import migrations, models


def copy_auditor_payment_verifications(apps, schema_editor):
    AuditorPaymentVerification = apps.get_model("core_system", "AuditorPaymentVerification")
    TransactionVerification = apps.get_model("core_system", "TransactionVerification")

    for apv in AuditorPaymentVerification.objects.iterator():
        table = apv.target_table
        qs = TransactionVerification.objects.filter(
            table_name=table,
            record_id=apv.target_record_id,
        )
        if qs.exists():
            qs.update(
                target_category="payment",
                auditor_remarks=apv.auditor_remarks or "",
                evidence_file_path=apv.evidence_file_path or "",
                evidence_file_hash=apv.evidence_file_hash or "",
            )


def copy_auditor_aid_verifications(apps, schema_editor):
    AuditorAidVerification = apps.get_model("core_system", "AuditorAidVerification")
    TransactionVerification = apps.get_model("core_system", "TransactionVerification")

    for aav in AuditorAidVerification.objects.iterator():
        table = aav.target_table
        qs = TransactionVerification.objects.filter(
            table_name=table,
            record_id=aav.target_record_id,
        )
        if qs.exists():
            qs.update(
                target_category="aid",
                auditor_remarks=aav.auditor_remarks or "",
                evidence_file_path=aav.evidence_file_path or "",
                evidence_file_hash=aav.evidence_file_hash or "",
            )


def copy_audit_log_to_global(apps, schema_editor):
    AuditLog = apps.get_model("core_system", "AuditLog")
    GlobalAuditTrail = apps.get_model("core_system", "GlobalAuditTrail")

    for log in AuditLog.objects.iterator():
        entity_type_map = {
            "MembershipFee": "membership_fee",
            "MonthlyDues": "monthly_dues",
            "MedicalAid": "medical_aid",
            "DeathAid": "death_aid",
        }
        table_name = entity_type_map.get(log.entity_type, log.entity_type.lower())
        record_id = None
        try:
            record_id = int(log.entity_id_id) if log.entity_id_id else None
        except (ValueError, TypeError):
            record_id = None

        if record_id is None:
            continue

        doc_archive_id = None
        if log.entity_id_id is not None:
            try:
                doc_archive_id = log.entity_id_id
            except Exception:
                doc_archive_id = None

        GlobalAuditTrail.objects.create(
            table_name=table_name,
            record_id=record_id,
            action=log.action.upper()[:20] if log.action else "UNKNOWN",
            actor_type=log.actor_type or "",
            actor_id=log.actor_id or None,
            actor_name="",
            ip_address=log.ip_address,
            notes=f"Migrated from AuditLog. Original action: {log.action}",
            document_archive_id_FK_id=doc_archive_id,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('core_system', '0019_aidtrackingpost_contribution'),
    ]

    operations = [
        # --- Schema additions ---
        migrations.AddField(
            model_name='globalaudittrail',
            name='document_archive_id_FK',
            field=models.ForeignKey(blank=True, db_column='document_archive_id_FK', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_trails', to='core_system.financialdocumentarchive'),
        ),
        migrations.AddField(
            model_name='transactionverification',
            name='auditor_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transactionverification',
            name='evidence_file_hash',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='transactionverification',
            name='evidence_file_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='transactionverification',
            name='return_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transactionverification',
            name='returned_by_auditor_id_FK',
            field=models.ForeignKey(blank=True, db_column='returned_by_auditor_id_FK', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_verifications_returned', to='core_system.officeruser'),
        ),
        migrations.AddField(
            model_name='transactionverification',
            name='returned_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transactionverification',
            name='target_category',
            field=models.CharField(blank=True, help_text="'payment' or 'aid' — replaces AuditorPaymentVerification/AuditorAidVerification", max_length=50, null=True),
        ),
        # --- Data migration: copy existing data from deprecated tables ---
        migrations.RunPython(copy_auditor_payment_verifications, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(copy_auditor_aid_verifications, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(copy_audit_log_to_global, reverse_code=migrations.RunPython.noop),
        # --- Drop deprecated tables ---
        migrations.DeleteModel(name='AuditorPaymentVerification'),
        migrations.DeleteModel(name='AuditorAidVerification'),
        migrations.DeleteModel(name='AuditLog'),
    ]
