# Generated by Django 5.2.14 on 2026-07-03 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_system', '0022_push_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='deathaid',
            name='bill_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='deathaid',
            name='funeral_location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='deathaid',
            name='interment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pushsubscription',
            name='officer_id_FK',
            field=models.ForeignKey(db_column='officer_id_FK', on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to='core_system.officeruser'),
        ),
    ]
