# Generated by Django 5.2.14 on 2026-07-03 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_system', '0023_death_aid_funeral_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimant',
            name='relationship_group',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='deathaid',
            name='relationship_group',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
