# Generated by Django 5.2.14 on 2026-07-06 01:37

from django.db import migrations
from core_system.constants.policy_constants import get_accidental_sickness_aid_benefit


def backfill_validated_amount(apps, schema_editor):
    MedicalAid = apps.get_model("core_system", "MedicalAid")
    amount = get_accidental_sickness_aid_benefit()
    MedicalAid.objects.filter(validated_aid_amount__isnull=True).update(validated_aid_amount=amount)
    MedicalAid.objects.filter(validated_aid_amount=0).update(validated_aid_amount=amount)


class Migration(migrations.Migration):

    dependencies = [
        ('core_system', '0026_sensitive_read_log'),
    ]

    operations = [
        migrations.RunPython(backfill_validated_amount, reverse_code=migrations.RunPython.noop),
    ]
