# Generated by Django 5.2.14 on 2026-07-06 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_system', '0029_backfill_department_fk'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('setting_id_PK', models.AutoField(primary_key=True, serialize=False)),
                ('setting_key', models.CharField(max_length=100, unique=True)),
                ('setting_value', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by_id_FK', models.ForeignKey(blank=True, db_column='updated_by_id_FK', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core_system.officeruser')),
            ],
            options={
                'db_table': 'SYSTEM_SETTING',
            },
        ),
    ]
