# Generated by Django 5.2.14 on 2026-07-06 17:38

from django.db import migrations


def seed_settings(apps, schema_editor):
    SystemSetting = apps.get_model("core_system", "SystemSetting")
    db_alias = schema_editor.connection.alias

    defaults = [
        ("grace_period_days", "15"),
        ("reminder_intervals", "[1, 3, 5, 7, 15]"),
        ("reminder_channels", '{"1": "email", "3": "email", "5": "sms", "7": "sms", "15": "email+sms"}'),
    ]
    for key, value in defaults:
        SystemSetting.objects.using(db_alias).get_or_create(
            setting_key=key,
            defaults={"setting_value": value},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('core_system', '0030_systemsetting'),
    ]

    operations = [
        migrations.RunPython(seed_settings, reverse_code=migrations.RunPython.noop),
    ]
