# Generated by Django 5.2.14 on 2026-07-06 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_system', '0031_seed_system_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='category',
            field=models.CharField(blank=True, help_text='dues, contribution, or general', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='channel',
            field=models.CharField(blank=True, help_text='email, sms, push', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='overdue_bucket',
            field=models.CharField(blank=True, help_text='1d, 3d, 5d, 7d, 15d+', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_post_id_FK',
            field=models.ForeignKey(blank=True, db_column='related_post_id_FK', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='core_system.aidtrackingpost'),
        ),
        migrations.AddField(
            model_name='notification',
            name='scheduled_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
