# Generated by Django 5.2.14 on 2026-07-06 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_system', '0032_notification_category_notification_channel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionarchive',
            name='fiscal_term',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='transactionverification',
            name='deposit_slip_reference',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
