# Generated by Django 5.2.14 on 2026-07-06 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_system', '0033_transactionarchive_fiscal_term_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aidtrackingpost',
            name='finish_skip_remaining',
            field=models.BooleanField(default=False, help_text='Whether to auto-skip unpaid contributions when President approves'),
        ),
        migrations.AddField(
            model_name='aidtrackingpost',
            name='finish_status',
            field=models.CharField(blank=True, default='', help_text="'' = no request, 'pending_approval' = awaiting President, 'rejected' = President rejected", max_length=20),
        ),
    ]
