# Generated by Django 5.2.5 on 2026-07-07 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_system', '0035_outbound_email'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='outboundemail',
            new_name='OUTBOUND_EM_status_87763e_idx',
            old_name='outbound_email_status_scheduled_idx',
        ),
    ]
