# Generated by Django 5.2.14 on 2026-07-07 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_system', '0036_rename_outbound_email_status_scheduled_idx_outbound_em_status_87763e_idx'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OutboundEmail',
        ),
    ]
