# Generated by Django 5.2.14 on 2026-07-09 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_system', '0037_delete_outboundemail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalaid',
            name='hospital_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
