# Generated by Django 5.2.5 on 2026-07-13 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_system', '0040_backfill_membership_fees'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollBatch',
            fields=[
                ('batch_id_PK', models.AutoField(primary_key=True, serialize=False)),
                ('payroll_period', models.CharField(help_text='YYYY-MM', max_length=7)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('member_count', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('hardcopy_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Auditor Verified', 'Auditor Verified'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Returned for Revision', 'Returned for Revision')], default='Pending', max_length=50)),
                ('auditor_verified_at', models.DateTimeField(blank=True, null=True)),
                ('auditor_remarks', models.TextField(blank=True, null=True)),
                ('returned_reason', models.TextField(blank=True, null=True)),
                ('president_approved_at', models.DateTimeField(blank=True, null=True)),
                ('president_remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archive_id_FK', models.ForeignKey(blank=True, db_column='archive_id_FK', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core_system.transactionarchive')),
                ('auditor_verified_by_user_id_FK', models.ForeignKey(blank=True, db_column='auditor_verified_by_user_id_FK', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_batches_verified', to='core_system.officeruser')),
                ('president_approved_by_user_id_FK', models.ForeignKey(blank=True, db_column='president_approved_by_user_id_FK', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_batches_approved', to='core_system.officeruser')),
                ('recorded_by_user_id_FK', models.ForeignKey(db_column='recorded_by_user_id_FK', on_delete=django.db.models.deletion.RESTRICT, related_name='payroll_batches_recorded', to='core_system.officeruser')),
                ('returned_by_user_id_FK', models.ForeignKey(blank=True, db_column='returned_by_user_id_FK', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_batches_returned', to='core_system.officeruser')),
            ],
            options={
                'db_table': 'PAYROLL_BATCH',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FundTransaction',
            fields=[
                ('transaction_id_PK', models.AutoField(primary_key=True, serialize=False)),
                ('direction', models.CharField(choices=[('inflow', 'Inflow'), ('outflow', 'Outflow')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('source_type', models.CharField(choices=[('payroll_batch', 'Payroll Batch'), ('death_aid', 'Death Aid Disbursement'), ('medical_aid', 'Medical Aid Disbursement'), ('membership_fee', 'Membership Fee'), ('monthly_dues', 'Monthly Dues'), ('contribution', 'Contribution'), ('manual_adjustment', 'Manual Adjustment')], max_length=50)),
                ('source_id', models.IntegerField(help_text='FK to the source record')),
                ('description', models.CharField(max_length=255)),
                ('reference_number', models.CharField(blank=True, help_text='Official reference / OR number', max_length=100, null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by_user_id_FK', models.ForeignKey(db_column='recorded_by_user_id_FK', on_delete=django.db.models.deletion.RESTRICT, related_name='fund_transactions', to='core_system.officeruser')),
            ],
            options={
                'db_table': 'FUND_TRANSACTION',
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['direction'], name='FUND_TRANSA_directi_c179cb_idx'), models.Index(fields=['source_type', 'source_id'], name='FUND_TRANSA_source__6023fe_idx')],
            },
        ),
        migrations.CreateModel(
            name='PayrollDeduction',
            fields=[
                ('deduction_id_PK', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('monthly_dues', 'Monthly Dues'), ('membership_fee', 'Membership Fee'), ('aid_contribution', 'Aid Contribution')], max_length=50)),
                ('fund_impact', models.CharField(choices=[('inflow', 'Inflow — replenishes the fund'), ('none', 'No fund impact — direct pass-through deduction')], default='inflow', help_text="'inflow' if replenishes fund, 'none' if direct pass-through", max_length=10)),
                ('month_covered', models.CharField(blank=True, help_text='YYYY-MM for monthly_dues', max_length=7, null=True)),
                ('notes', models.TextField(blank=True)),
                ('aid_tracking_post_id_FK', models.ForeignKey(blank=True, db_column='aid_tracking_post_id_FK', help_text='Links to the aid disbursement this contribution repays', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core_system.aidtrackingpost')),
                ('batch_id_FK', models.ForeignKey(db_column='batch_id_FK', on_delete=django.db.models.deletion.CASCADE, related_name='deductions', to='core_system.payrollbatch')),
                ('member_id_FK', models.ForeignKey(db_column='member_id_FK', on_delete=django.db.models.deletion.RESTRICT, to='core_system.member')),
            ],
            options={
                'db_table': 'PAYROLL_DEDUCTION',
                'indexes': [models.Index(fields=['batch_id_FK', 'category'], name='PAYROLL_DED_batch_i_0b9b21_idx'), models.Index(fields=['member_id_FK'], name='PAYROLL_DED_member__4008e1_idx')],
            },
        ),
    ]
