# Generated by Django 5.2.5 on 2026-07-13 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_system', '0041_payrollbatch_fundtransaction_payrolldeduction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aidtrackingpost',
            name='finish_skip_remaining',
        ),
        migrations.RemoveField(
            model_name='aidtrackingpost',
            name='finish_status',
        ),
        migrations.AddField(
            model_name='aidtrackingpost',
            name='source_id',
            field=models.IntegerField(blank=True, help_text='PK of the DeathAid or MedicalAid record', null=True),
        ),
        migrations.AddField(
            model_name='aidtrackingpost',
            name='source_type',
            field=models.CharField(blank=True, help_text="'death_aid' or 'medical_aid' — the aid that triggered this tracking post", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='aidtrackingpost',
            name='status',
            field=models.CharField(choices=[('tracking', 'Tracking — members are being charged'), ('closed', 'Closed — all tracked')], default='tracking', max_length=20),
        ),
        migrations.AddField(
            model_name='deathaid',
            name='disbursement_source',
            field=models.CharField(blank=True, choices=[('fund', 'Fund — paid from org fund'), ('direct', 'Direct — payroll deduction, no fund impact')], help_text='How was this aid funded?', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='medicalaid',
            name='disbursement_source',
            field=models.CharField(blank=True, choices=[('fund', 'Fund — paid from org fund'), ('direct', 'Direct — payroll deduction, no fund impact')], help_text='How was this aid funded?', max_length=20, null=True),
        ),
    ]
