# Generated by Django 5.2.14 on 2026-07-14 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_system', '0042_remove_aidtrackingpost_finish_skip_remaining_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aidtrackingpost',
            name='finish_skip_remaining',
            field=models.BooleanField(default=False, help_text='Whether to auto-skip unpaid contributions when President approves'),
        ),
        migrations.AddField(
            model_name='aidtrackingpost',
            name='finish_status',
            field=models.CharField(blank=True, default='', help_text="'' = no request, 'pending_approval' = awaiting President, 'rejected' = President rejected, 'paid_with_funds' = fund disbursement", max_length=20),
        ),
    ]
