# Generated by Django 5.2.14 on 2026-07-14 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_system', '0043_aidtrackingpost_finish_status_paid_with_funds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundtransaction',
            name='source_type',
            field=models.CharField(choices=[('payroll_batch', 'Payroll Batch'), ('death_aid', 'Death Aid Disbursement'), ('medical_aid', 'Medical Aid Disbursement'), ('membership_fee', 'Membership Fee'), ('monthly_dues', 'Monthly Dues'), ('contribution', 'Contribution'), ('manual_adjustment', 'Manual Adjustment'), ('aid_post_payment', 'Aid Post Fund Payment')], max_length=50),
        ),
        migrations.CreateModel(
            name='OrganizationFundReport',
            fields=[
                ('report_id_PK', models.AutoField(primary_key=True, serialize=False)),
                ('report_period', models.CharField(max_length=20)),
                ('report_type', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=20)),
                ('report_status', models.CharField(choices=[('Draft', 'Draft'), ('Submitted', 'Submitted'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Draft', max_length=50)),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by_user_id_FK', models.ForeignKey(blank=True, db_column='approved_by_user_id_FK', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fund_reports_approved', to='core_system.officeruser')),
                ('prepared_by_user_id_FK', models.ForeignKey(db_column='prepared_by_user_id_FK', on_delete=django.db.models.deletion.RESTRICT, related_name='fund_reports_prepared', to='core_system.officeruser')),
            ],
            options={
                'db_table': 'ORGANIZATION_FUND_REPORT',
                'ordering': ['-created_at'],
            },
        ),
    ]
