# Generated by Django 5.2.14 on 2026-07-15 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_system', '0045_alter_member_employee_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutgoingEmail',
            fields=[
                ('outgoing_email_id', models.AutoField(primary_key=True, serialize=False)),
                ('recipient_list', models.JSONField(default=list)),
                ('subject', models.CharField(max_length=255)),
                ('html_template', models.CharField(max_length=255)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('retry_count', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'OUTGOING_EMAIL',
                'ordering': ['created_at'],
            },
        ),
    ]
