# Generated by Django 5.2.14 on 2026-07-15 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_system', '0046_outgoingemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='aidtrackingpost',
            name='finish_paid_with_funds',
            field=models.BooleanField(default=False, help_text='True when the post was paid using organizational funds instead of member contributions'),
        ),
    ]
