# Generated by Django 5.2.14 on 2026-07-16 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_system', '0047_aidtrackingpost_finish_paid_with_funds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aidtrackingpost',
            name='finish_status',
            field=models.CharField(blank=True, default='', help_text="'' = no request, 'pending_approval' = awaiting President, 'rejected' = rejected, 'pending_release' = awaiting Treasurer fund release, 'pending_auditor' = awaiting Auditor verification, 'pending_president' = awaiting President, 'repayment' = fund released, members still owe", max_length=20),
        ),
    ]
