# Generated by Django 5.2.5 on 2026-07-16 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_system', '0052_migrate_bylaws_to_bylawsfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='officeruser',
            name='mfa_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
