# Generated by Django 5.2.5 on 2026-07-16 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_system', '0053_officeruser_mfa_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='officeruser',
            name='last_mfa_email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
