# Generated by Django 5.2.5 on 2026-07-16 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_system', '0054_officeruser_last_mfa_email_sent_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesssession',
            name='last_verified_location',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accesssession',
            name='session_policy',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accesssession',
            name='trusted_device',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='globalaudittrail',
            name='entry_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='globalaudittrail',
            name='hmac_signature',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='globalaudittrail',
            name='previous_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
