# Generated by Django 5.2.16 on 2026-07-16 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_system', '0055_accesssession_last_verified_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupJob',
            fields=[
                ('job_id', models.AutoField(primary_key=True, serialize=False)),
                ('backup_type', models.CharField(choices=[('db', 'Database'), ('media', 'Media'), ('config', 'Config')], max_length=20)),
                ('backup_status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Failed', 'Failed')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('db_dump_path', models.CharField(blank=True, max_length=500, null=True)),
                ('media_archive_path', models.CharField(blank=True, max_length=500, null=True)),
                ('metadata_json', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'BACKUP_JOB',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='member',
            name='officer_user_id_FK',
            field=models.ForeignKey(blank=True, db_column='officer_user_id_FK', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_member_profiles', to='core_system.officeruser'),
        ),
        migrations.AddField(
            model_name='officeruser',
            name='department_id_FK',
            field=models.ForeignKey(blank=True, db_column='department_id_FK', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='officers', to='core_system.department'),
        ),
    ]
