# Generated by Django 5.2.5 on 2026-07-17 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_system', '0057_seed_departments'),
    ]

    operations = [
        migrations.AddField(
            model_name='officeruser',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
