# Generated by Django 5.2.16 on 2026-07-17 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_system', '0060_add_deduction_remittance_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundtransaction',
            name='source_type',
            field=models.CharField(choices=[('payroll_batch', 'Payroll Batch'), ('death_aid', 'Death Aid Disbursement'), ('medical_aid', 'Medical Aid Disbursement'), ('membership_fee', 'Membership Fee'), ('monthly_dues', 'Monthly Dues'), ('contribution', 'Contribution'), ('manual_adjustment', 'Manual Adjustment'), ('aid_post_payment', 'Aid Post Fund Payment'), ('salary_deduction_remittance', 'Salary Deduction Remittance')], max_length=50),
        ),
        migrations.AlterField(
            model_name='globalaudittrail',
            name='action',
            field=models.CharField(max_length=50),
        ),
    ]
