# Generated by Django 5.2.16 on 2026-07-18 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_system', '0061_increase_audit_trail_action_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensitivereadlog',
            name='device_info',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
