# Generated by Django 5.2.16 on 2026-07-18 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_system', '0062_add_sensitive_read_log_device_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribution',
            name='status',
            field=models.CharField(choices=[('NOT_PAID', 'Not Paid'), ('RECORDED', 'Recorded'), ('PENDING_VERIFICATION', 'Pending Verification'), ('PAID', 'Paid'), ('SKIPPED', 'Skipped')], default='NOT_PAID', max_length=20),
        ),
    ]
