# Generated by Django 5.2.16 on 2026-07-23 00:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_system', '0063_add_contribution_recorded_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberRegistrationRequest',
            fields=[
                ('request_id_PK', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('employee_id', models.CharField(max_length=50)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('position', models.CharField(blank=True, max_length=100, null=True)),
                ('membership_category', models.CharField(default='Permanent', max_length=50)),
                ('payment_method', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, default=100, max_digits=10)),
                ('receipt_number', models.CharField(max_length=100)),
                ('reference_number', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='Pending Treasurer Review', max_length=50)),
                ('returned_reason', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_by_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('submitted_by_user_agent', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'MEMBER_REGISTRATION_REQUEST',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.AddField(
            model_name='memberregistrationrequest',
            name='processed_by_user_id_FK',
            field=models.ForeignKey(blank=True, db_column='processed_by_user_id_FK', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_registration_requests', to='core_system.officeruser'),
        ),
    ]
