# Generated by Django 5.2.7 on 2026-07-23 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_system', '0068_member_profile_picture'),
    ]

    operations = [
        # Only add MedicalAid fields in this migration to avoid applying
        # sensitive_read_log schema changes that may not match the target DB.
        migrations.AddField(
            model_name='medicalaid',
            name='admission_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalaid',
            name='discharge_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalaid',
            name='hospital_address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='medicalaid',
            name='reason_for_request',
            field=models.TextField(blank=True, null=True),
        ),
    ]
