# Generated by Django 5.2.16 on 2026-07-24 03:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_system', '0069_rename_sensitive_r_table_n_c95688_idx_sensitive_r_module_b2b1eb_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberregistrationrequest',
            name='auditor_verified_by_user_id_FK',
            field=models.ForeignKey(blank=True, db_column='auditor_verified_by_user_id_FK', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditor_verified_registrations', to='core_system.officeruser'),
        ),
        migrations.AddField(
            model_name='memberregistrationrequest',
            name='president_approved_by_user_id_FK',
            field=models.ForeignKey(blank=True, db_column='president_approved_by_user_id_FK', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='president_approved_registrations', to='core_system.officeruser'),
        ),
        migrations.AddField(
            model_name='memberregistrationrequest',
            name='treasurer_verified_by_user_id_FK',
            field=models.ForeignKey(blank=True, db_column='treasurer_verified_by_user_id_FK', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treasurer_verified_registrations', to='core_system.officeruser'),
        ),
    ]
