# Generated by Django 5.2.7 on 2026-07-24 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_system', '0070_registration_workflow_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='deathaid',
            name='date_of_death',
            field=models.DateField(blank=True, null=True),
        ),
    ]
