# Generated by Django 5.2.7 on 2026-07-24 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_system', '0071_rename_sensitive_r_table_n_c95688_idx_sensitive_r_module_b2b1eb_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(default=False, db_column='is_read'),
        ),
    ]
