# Generated by Django 5.2.7 on 2026-07-24 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_system', '0073_add_is_read_to_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlydues',
            name='treasurer_status',
            field=models.CharField(default='Pending Treasurer Review', db_column='treasurer_status', max_length=50),
        ),
        migrations.AddField(
            model_name='monthlydues',
            name='treasurer_id_FK',
            field=models.ForeignKey(db_column='treasurer_id_FK', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monthly_dues_treasurer_approved', to='core_system.officeruser', blank=True),
        ),
        migrations.AddField(
            model_name='monthlydues',
            name='treasurer_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monthlydues',
            name='treasurer_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monthlydues',
            name='auditor_status',
            field=models.CharField(default='Pending Auditor Review', db_column='auditor_status', max_length=50),
        ),
        migrations.AddField(
            model_name='monthlydues',
            name='auditor_id_FK',
            field=models.ForeignKey(db_column='auditor_id_FK', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monthly_dues_auditor_approved', to='core_system.officeruser', blank=True),
        ),
        migrations.AddField(
            model_name='monthlydues',
            name='auditor_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monthlydues',
            name='auditor_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monthlydues',
            name='president_status',
            field=models.CharField(default='Pending President Approval', db_column='president_status', max_length=50),
        ),
        migrations.AddField(
            model_name='monthlydues',
            name='president_id_FK',
            field=models.ForeignKey(db_column='president_id_FK', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monthly_dues_president_approved', to='core_system.officeruser', blank=True),
        ),
        migrations.AddField(
            model_name='monthlydues',
            name='president_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monthlydues',
            name='president_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
