# Generated by Django 5.2.7 on 2026-07-24 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_system', '0074_add_approval_fields_to_monthly_dues'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberLedger',
            fields=[
                ('ledger_id_PK', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(help_text='membership_fee, monthly_dues, contribution, medical_aid, death_aid, refund, adjustment', max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('direction', models.CharField(help_text='credit or debit', max_length=10)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reference_id', models.IntegerField(blank=True, help_text='FK to the source record (MonthlyDues, MembershipFee, etc.)', null=True)),
                ('reference_type', models.CharField(blank=True, help_text='The model name of the reference', max_length=50, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('member_id_FK', models.ForeignKey(db_column='member_id_FK', on_delete=django.db.models.deletion.RESTRICT, related_name='ledger_entries', to='core_system.member')),
                ('recorded_by_user_id_FK', models.ForeignKey(db_column='recorded_by_user_id_FK', on_delete=django.db.models.deletion.RESTRICT, related_name='ledger_entries_recorded', to='core_system.officeruser')),
            ],
            options={
                'db_table': 'MEMBER_LEDGER',
                'ordering': ['-recorded_at'],
                'indexes': [
                    models.Index(fields=['member_id_FK'], name='MEMBER_LEDG_member__9bc074_idx'),
                    models.Index(fields=['transaction_type'], name='MEMBER_LEDG_transac_4c41b6_idx'),
                    models.Index(fields=['recorded_at'], name='MEMBER_LEDG_recorde_fa4ecd_idx'),
                ],
            },
        ),
    ]
