# Generated by Django 5.2.7 on 2026-07-24 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_system', '0075_add_member_ledger_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('attendance_id_PK', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('check_in_time', models.TimeField(blank=True, null=True)),
                ('check_out_time', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(default='Present', max_length=20)),
                ('check_in_method', models.CharField(default='PIN', max_length=20)),
                ('member_id_FK', models.ForeignKey(db_column='member_id_FK', on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='core_system.member')),
            ],
            options={
                'db_table': 'ATTENDANCE',
            },
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('member_id_FK', 'date')},
        ),
    ]
