# Generated by Django 5.2.7 on 2026-07-25 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_system', '0077_add_member_onboarding_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
    ]
