# Generated by Django 5.2.7 on 2026-07-26 00:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_system', '0079_fix_attendance_member_fk'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('announcement_id_PK', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Meeting Notice', 'Meeting Notice'), ('Event Announcement', 'Event Announcement'), ('General Announcement', 'General Announcement'), ('Organization Update', 'Organization Update')], max_length=50)),
                ('description', models.TextField()),
                ('attachment_path', models.CharField(blank=True, max_length=500)),
                ('attachment_name', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ANNOUNCEMENT',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('document_id_PK', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('document_type', models.CharField(choices=[('Constitution', 'Constitution'), ('By-Laws', 'By-Laws'), ('Minutes of Meeting', 'Minutes of Meeting'), ('Memorandum', 'Memorandum'), ('Office Order', 'Office Order'), ('Resolution', 'Resolution'), ('Circular', 'Circular'), ('Activity Report', 'Activity Report'), ('Financial Document', 'Financial Document'), ('Certificate', 'Certificate'), ('Other', 'Other')], max_length=50)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('keywords', models.CharField(blank=True, max_length=500)),
                ('tags', models.CharField(blank=True, max_length=500)),
                ('file_path', models.CharField(max_length=500)),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('file_type', models.CharField(blank=True, max_length=50)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('retention_period', models.DateField(blank=True, null=True)),
                ('is_archived', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'DOCUMENT',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id_PK', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('venue', models.CharField(max_length=255)),
                ('event_date', models.DateField()),
                ('event_time', models.TimeField()),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('event_type', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Upcoming', 'Upcoming'), ('Ongoing', 'Ongoing'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Upcoming', max_length=20)),
                ('attendance_open', models.BooleanField(default=False)),
                ('attendance_closed', models.BooleanField(default=False)),
                ('quorum_required', models.IntegerField(default=60)),
                ('quorum_reached', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'EVENT',
                'ordering': ['-event_date', '-event_time'],
            },
        ),
        migrations.CreateModel(
            name='Minutes',
            fields=[
                ('minutes_id_PK', models.AutoField(primary_key=True, serialize=False)),
                ('meeting_title', models.CharField(max_length=255)),
                ('meeting_date', models.DateField()),
                ('venue', models.CharField(max_length=255)),
                ('attendees', models.TextField(blank=True)),
                ('agenda', models.TextField(blank=True)),
                ('minutes_content', models.TextField()),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Pending', 'Pending'), ('Finalized', 'Finalized')], default='Draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'MINUTES',
                'ordering': ['-meeting_date'],
            },
        ),
        migrations.AddField(
            model_name='announcement',
            name='published_by_user_id_FK',
            field=models.ForeignKey(blank=True, db_column='published_by_user_id_FK', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_announcements', to='core_system.officeruser'),
        ),
        migrations.AddField(
            model_name='document',
            name='uploaded_by_user_id_FK',
            field=models.ForeignKey(blank=True, db_column='uploaded_by_user_id_FK', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to='core_system.officeruser'),
        ),
        migrations.AddField(
            model_name='event',
            name='created_by_user_id_FK',
            field=models.ForeignKey(blank=True, db_column='created_by_user_id_FK', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_events', to='core_system.officeruser'),
        ),
        migrations.AddField(
            model_name='minutes',
            name='document_id_FK',
            field=models.ForeignKey(blank=True, db_column='document_id_FK', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_minutes', to='core_system.document'),
        ),
        migrations.AddField(
            model_name='minutes',
            name='event_id_FK',
            field=models.ForeignKey(blank=True, db_column='event_id_FK', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meeting_minutes', to='core_system.event'),
        ),
        migrations.AddField(
            model_name='minutes',
            name='prepared_by_user_id_FK',
            field=models.ForeignKey(blank=True, db_column='prepared_by_user_id_FK', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prepared_minutes', to='core_system.officeruser'),
        ),
    ]
