# Generated by Django 5.2.7 on 2026-07-26 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_system', '0081_add_missing_secretary_fks'),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='Certificate',
        #     fields=[
        #         ('certificate_id_PK', models.AutoField(primary_key=True, serialize=False)),
        #         ('certificate_number', models.CharField(max_length=50, unique=True)),
        #         ('pdf_file', models.FileField(blank=True, null=True, upload_to='certificates/')),
        #         ('email_status', models.CharField(choices=[('Pending', 'Pending'), ('Sent', 'Sent'), ('Failed', 'Failed')], default='Pending', max_length=20)),
        #         ('email_sent_at', models.DateTimeField(blank=True, null=True)),
        #         ('email_error', models.TextField(blank=True)),
        #         ('generated_at', models.DateTimeField(auto_now_add=True)),
        #         ('downloaded_at', models.DateTimeField(blank=True, null=True)),
        #     ],
        #     options={
        #         'db_table': 'CERTIFICATE',
        #         'ordering': ['-generated_at'],
        #     },
        # ),
        # migrations.CreateModel(
        #     name='CertificateSettings',
        #     fields=[
        #         ('settings_id_PK', models.AutoField(primary_key=True, serialize=False)),
        #         ('president_name', models.CharField(help_text='Name of ISUCauFA President', max_length=255)),
        #         ('president_position', models.CharField(default='ISUCauFA President', max_length=255)),
        #         ('president_signature', models.ImageField(blank=True, help_text='Upload PNG with transparent background', null=True, upload_to='signatures/')),
        #         ('secretary_name', models.CharField(help_text='Name of ISUCauFA Secretary', max_length=255)),
        #         ('secretary_position', models.CharField(default='ISUCauFA, Inc. Secretary', max_length=255)),
        #         ('secretary_signature', models.ImageField(blank=True, help_text='Upload PNG with transparent background', null=True, upload_to='signatures/')),
        #         ('faculty_regent_name', models.CharField(blank=True, help_text='Name of Faculty Regent or Authorized Official', max_length=255)),
        #         ('faculty_regent_position', models.CharField(default='Faculty Regent', max_length=255)),
        #         ('faculty_regent_signature', models.ImageField(blank=True, help_text='Upload PNG with transparent background', null=True, upload_to='signatures/')),
        #         ('organization_logo', models.ImageField(blank=True, help_text='Organization logo for certificate', null=True, upload_to='logos/')),
        #         ('header_text', models.CharField(default='Republic of the Philippines', max_length=255)),
        #         ('footer_text', models.TextField(blank=True, help_text='Optional footer text for certificate')),
        #         ('updated_at', models.DateTimeField(auto_now=True)),
        #     ],
        #     options={
        #         'verbose_name_plural': 'Certificate Settings',
        #         'db_table': 'CERTIFICATE_SETTINGS',
        #     },
        # ),
        # migrations.RenameIndex(
        #     model_name='sensitivereadlog',
        #     new_name='SENSITIVE_R_module_b2b1eb_idx',
        #     old_name='SENSITIVE_R_table_n_c95688_idx',
        # ),
        # migrations.RenameIndex(
        #     model_name='sensitivereadlog',
        #     new_name='SENSITIVE_R_timesta_d47548_idx',
        #     old_name='SENSITIVE_R_read_at_121b97_idx',
        # ),
        # migrations.RemoveField(
        #     model_name='sensitivereadlog',
        #     name='description',
        # ),
        # migrations.RemoveField(
        #     model_name='sensitivereadlog',
        #     name='ip_address',
        # ),
        # migrations.RemoveField(
        #     model_name='sensitivereadlog',
        #     name='reader_name',
        # ),
        migrations.AddField(
            model_name='event',
            name='auto_generate_certificates',
            field=models.BooleanField(default=False, help_text='Automatically generate certificates on event completion'),
        ),
        migrations.AddField(
            model_name='event',
            name='certificate_issue_date',
            field=models.DateField(blank=True, help_text='Date certificate is issued', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='certificate_prefix',
            field=models.CharField(blank=True, default='ISUCauFA-ATT', help_text='Prefix for certificate numbers', max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='given_place',
            field=models.CharField(blank=True, help_text='Place where certificate is given', max_length=255),
        ),
        # migrations.AlterField(
        #     model_name='sensitivereadlog',
        #     name='read_at',
        #     field=models.DateTimeField(auto_now_add=True, db_column='timestamp'),
        # ),
        # migrations.AlterField(
        #     model_name='sensitivereadlog',
        #     name='read_id',
        #     field=models.AutoField(db_column='read_id_PK', primary_key=True, serialize=False),
        # ),
        # migrations.AlterField(
        #     model_name='sensitivereadlog',
        #     name='reader_id',
        #     field=models.IntegerField(blank=True, db_column='user_id_FK', null=True),
        # ),
        # migrations.AlterField(
        #     model_name='sensitivereadlog',
        #     name='reader_type',
        #     field=models.CharField(db_column='purpose', default='', max_length=50),
        # ),
        # migrations.AlterField(
        #     model_name='sensitivereadlog',
        #     name='table_name',
        #     field=models.CharField(db_column='module', max_length=100),
        # ),
        # migrations.AddField(
        #     model_name='certificate',
        #     name='event',
        #     field=models.ForeignKey(db_column='event_id_FK', on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='core_system.event'),
        # ),
        # migrations.AddField(
        #     model_name='certificate',
        #     name='member',
        #     field=models.ForeignKey(db_column='member_id_FK', on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='core_system.member'),
        # ),
        # migrations.AlterUniqueTogether(
        #     name='certificate',
        #     unique_together={('member', 'event')},
        # ),
    ]
