# Generated by Django 5.2.7 on 2026-07-27 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_system', '0082_certificate_certificatesettings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='event_id_FK',
            field=models.ForeignKey(blank=True, db_column='event_id_FK', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='core_system.event'),
        ),
    ]
