# Generated by Django 5.2.7 on 2026-07-31 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_system', '0090_pio_album_cover_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficerProfile',
            fields=[
                ('officer_profile_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Executive Officer', 'Executive Officer'), ('Board of Directors', 'Board of Directors'), ('Adviser', 'Adviser')], default='Executive Officer', max_length=50)),
                ('department', models.CharField(blank=True, max_length=255, null=True)),
                ('school_year', models.CharField(blank=True, max_length=50, null=True)),
                ('term_start', models.DateField(blank=True, null=True)),
                ('term_end', models.DateField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('biography', models.TextField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='officer_profiles/')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_officer_profiles', to='core_system.officeruser')),
            ],
            options={
                'db_table': 'OFFICER_PROFILE',
                'ordering': ['category', 'position', 'full_name'],
            },
        ),
    ]
