# Generated by Django 5.2.7 on 2026-07-31 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_system', '0092_announcementcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('news_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('summary', models.TextField(help_text='Brief summary for article cards', max_length=500)),
                ('content', models.TextField(help_text='Full article content (supports HTML)')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='news/%Y/%m/')),
                ('event_date', models.DateField(blank=True, null=True)),
                ('event_time', models.TimeField(blank=True, null=True)),
                ('venue', models.CharField(blank=True, max_length=255)),
                ('video_url', models.URLField(blank=True, help_text='YouTube or other video platform URL')),
                ('video_thumbnail', models.ImageField(blank=True, null=True, upload_to='news/%Y/%m/')),
                ('is_featured', models.BooleanField(default=False, help_text='Show in featured news section')),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('view_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'News Article',
                'verbose_name_plural': 'News Articles',
                'db_table': 'NEWS_ARTICLE',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsCategory',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='Font Awesome icon class', max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'News Categories',
                'db_table': 'NEWS_CATEGORY',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='NewsGallery',
            fields=[
                ('gallery_id', models.AutoField(primary_key=True, serialize=False)),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(upload_to='news/%Y/%m/')),
                ('is_featured', models.BooleanField(default=False, help_text='Featured image in article gallery')),
                ('order', models.IntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'News Galleries',
                'db_table': 'NEWS_GALLERY',
                'ordering': ['order', '-uploaded_at'],
            },
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_news', to='core_system.officeruser'),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='core_system.newscategory'),
        ),
        migrations.AddField(
            model_name='newsgallery',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galleries', to='core_system.newsarticle'),
        ),
    ]
