# Generated by Django 5.2.16 on 2026-08-01 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_system', '0097_heroslide_remove_newsarticle_is_hero'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='announcements/%Y/%m/'),
        ),
    ]
