# Generated by Django 5.2.16 on 2026-08-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_system', '0098_add_announcement_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='bylawsfile',
            name='document_type',
            field=models.CharField(
                choices=[
                    ('Constitution', 'Constitution'),
                    ('By-Laws', 'By-Laws'),
                    ('Other', 'Other'),
                ],
                default='By-Laws',
                max_length=50,
            ),
        ),
    ]
