# Generated by Django 5.2.7 on 2026-08-05 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_system', '0100_bylaws_public_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesssession',
            name='last_activity_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
