# Generated by Django 5.2.7 on 2026-08-05 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_system', '0101_accesssession_last_activity_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='officeruser',
            name='must_change_password',
            field=models.BooleanField(default=False),
        ),
    ]
