# Generated by Django 5.2.7 on 2026-08-05 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_system', '0102_officeruser_must_change_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlydues',
            name='is_advance',
            field=models.BooleanField(db_column='is_advance', default=False, help_text='True when the covered month is in the future (early/advance payment).'),
        ),
    ]
