# Generated by Django 5.2.7 on 2026-08-06 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_system', '0103_monthlydues_is_advance'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryDeductionExemption',
            fields=[
                ('exemption_id_PK', models.AutoField(primary_key=True, serialize=False)),
                ('month_covered', models.CharField(max_length=50)),
                ('reason', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='Pending', help_text='Pending, Approved, Rejected', max_length=50)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('requested_by_member', models.BooleanField(default=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_remarks', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'salary_deduction_exemption',
            },
        ),
        migrations.RemoveIndex(
            model_name='transactionarchive',
            name='transaction_transac_4a6ac9_idx',
        ),
        migrations.RemoveIndex(
            model_name='transactionarchive',
            name='transaction_status_abeab9_idx',
        ),
        migrations.AlterField(
            model_name='transactionarchive',
            name='archived_by_user_id_FK',
            field=models.ForeignKey(blank=True, db_column='archived_by_user_id_FK', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_by', to='core_system.officeruser'),
        ),
        migrations.AddField(
            model_name='salarydeductionexemption',
            name='member_id_FK',
            field=models.ForeignKey(db_column='member_id_FK', on_delete=django.db.models.deletion.CASCADE, related_name='salary_deduction_exemptions', to='core_system.member'),
        ),
        migrations.AddField(
            model_name='salarydeductionexemption',
            name='reviewed_by_user_id_FK',
            field=models.ForeignKey(blank=True, db_column='reviewed_by_user_id_FK', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_exemptions', to='core_system.officeruser'),
        ),
        migrations.AlterUniqueTogether(
            name='salarydeductionexemption',
            unique_together={('member_id_FK', 'month_covered')},
        ),
    ]
