# Generated by Django 5.2.16 on 2026-08-08 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_system', '0104_salarydeductionexemption_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='receipt_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='sender_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='sender_role',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
