# Generated by Django 5.2.16 on 2026-08-08 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_system', '0105_notification_sender_receipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribution',
            name='status',
            field=models.CharField(choices=[('NOT_PAID', 'Not Paid'), ('RECORDED', 'Recorded'), ('PENDING_VERIFICATION', 'Pending Verification'), ('PAID', 'Paid'), ('SKIPPED', 'Skipped'), ('EXCLUDED_REQUESTER', 'Excluded (Requester)')], default='NOT_PAID', max_length=20),
        ),
    ]
