# Generated by Django 5.2.16 on 2026-08-10 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_system', '0106_add_excluded_requester_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pushsubscription',
            unique_together={('officer_id_FK', 'endpoint')},
        ),
        migrations.AddField(
            model_name='pushsubscription',
            name='member_id_FK',
            field=models.ForeignKey(blank=True, db_column='member_id_FK', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to='core_system.member'),
        ),
        migrations.AlterField(
            model_name='pushsubscription',
            name='officer_id_FK',
            field=models.ForeignKey(blank=True, db_column='officer_id_FK', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to='core_system.officeruser'),
        ),
        migrations.AlterUniqueTogether(
            name='pushsubscription',
            unique_together={('member_id_FK', 'endpoint'), ('officer_id_FK', 'endpoint')},
        ),
    ]
