# Generated by Django 5.2.16 on 2026-08-10 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_system', '0107_add_member_push_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='aidtrackingpost',
            name='finish_cycle',
            field=models.PositiveSmallIntegerField(default=0, help_text='0 = initial collection, 1 = first cycle (paid with funds), 2 = repayment close cycle'),
        ),
    ]
