# Generated by Django 5.2.7 on 2026-08-10 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_system', '0108_aidtrackingpost_finish_cycle'),
    ]

    operations = [
        migrations.AddField(
            model_name='aidtrackingpost',
            name='collection_started',
            field=models.BooleanField(default=False, help_text='Whether the treasurer has started collecting contributions for this post'),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='status',
            field=models.CharField(choices=[('NOT_PAID', 'Not Paid'), ('RECORDED', 'Recorded'), ('PENDING_VERIFICATION', 'Pending Verification'), ('PAID', 'Paid'), ('SKIPPED', 'Skipped'), ('EXCLUDED_REQUESTER', 'Not Included (Requester)')], default='NOT_PAID', max_length=20),
        ),
    ]
