# Generated by Django 5.2.7 on 2026-08-14 03:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_system', '0109_aidtrackingpost_collection_started_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PositionRank',
            fields=[
                ('position_rank_id_PK', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('Instructor', 'Instructor'), ('Assistant Professor', 'Assistant Professor'), ('Associate Professor', 'Associate Professor'), ('Full Professor', 'Full Professor'), ('Administrative', 'Administrative'), ('Staff', 'Staff'), ('Other', 'Other')], default='Other', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by_user_id_FK', models.ForeignKey(blank=True, db_column='created_by_user_id_FK', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core_system.officeruser')),
            ],
            options={
                'db_table': 'position_rank',
                'ordering': ['category', 'name'],
            },
        ),
    ]
