# Generated by Django 5.2.7 on 2026-08-15 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_system', '0110_positionrank'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='role',
            field=models.CharField(default='Secretary', max_length=50),
        ),
    ]
