# Generated by Django 5.2.16 on 2026-08-17 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_system', '0111_add_category_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='pushsubscription',
            name='origin',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
