# Generated by Django 5.2.7 on 2026-09-09 11:56

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_system', '0122_repair_member_status_values'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyAssessment',
            fields=[
                ('assessment_id_PK', models.AutoField(primary_key=True, serialize=False)),
                ('month', models.DateField(help_text='First day of the covered month (e.g. 2026-09-01 for September 2026).', unique=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_audit', 'Pending Auditor Verification'), ('pending_final', 'Pending President Approval'), ('final_approved', 'Final Approved'), ('rejected', 'Rejected by Auditor'), ('returned', 'Returned by President')], default='draft', max_length=50)),
                ('treasurer_remarks', models.TextField(blank=True, null=True)),
                ('auditor_remarks', models.TextField(blank=True, null=True)),
                ('president_remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_id_FK', models.ForeignKey(blank=True, db_column='created_by_id_FK', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monthly_assessments_created', to='core_system.officeruser')),
            ],
            options={
                'db_table': 'monthly_assessments',
                'ordering': ['-month'],
            },
        ),
        migrations.CreateModel(
            name='MemberAssessment',
            fields=[
                ('member_assessment_id_PK', models.AutoField(primary_key=True, serialize=False)),
                ('standard_assessment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('actual_deduction', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('outstanding_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending Verification'), ('verified', 'Verified by Auditor'), ('approved', 'Final Approved')], default='pending', max_length=50)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by_id_FK', models.ForeignKey(blank=True, db_column='approved_by_id_FK', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_assessments_approved', to='core_system.officeruser')),
                ('member_id_FK', models.ForeignKey(db_column='member_id_FK', on_delete=django.db.models.deletion.RESTRICT, related_name='monthly_assessment_deductions', to='core_system.member')),
                ('recorded_by_id_FK', models.ForeignKey(blank=True, db_column='recorded_by_id_FK', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_assessments_recorded', to='core_system.officeruser')),
                ('verified_by_id_FK', models.ForeignKey(blank=True, db_column='verified_by_id_FK', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_assessments_verified', to='core_system.officeruser')),
                ('assessment_id_FK', models.ForeignKey(db_column='assessment_id_FK', on_delete=django.db.models.deletion.CASCADE, related_name='member_assessments', to='core_system.monthlyassessment')),
            ],
            options={
                'db_table': 'member_assessments',
                'ordering': ['member_id_FK__full_name'],
                'unique_together': {('assessment_id_FK', 'member_id_FK')},
            },
        ),
        migrations.CreateModel(
            name='AssessmentWorkflowLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performed_by_id_FK', models.ForeignKey(blank=True, db_column='performed_by_id_FK', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessment_workflow_actions', to='core_system.officeruser')),
                ('assessment_id_FK', models.ForeignKey(db_column='assessment_id_FK', on_delete=django.db.models.deletion.CASCADE, related_name='workflow_logs', to='core_system.monthlyassessment')),
            ],
            options={
                'db_table': 'workflow_logs',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentItem',
            fields=[
                ('item_id_PK', models.AutoField(primary_key=True, serialize=False)),
                ('purpose', models.CharField(choices=[('monthly_due', 'Monthly Due'), ('medical_aid_fund', 'Medical Aid Fund'), ('death_aid_fund', 'Death Aid Fund'), ('token_incentive', 'Token Incentive'), ('other', 'Other')], max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('recipient', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('priority_order', models.IntegerField(default=1, help_text="Lower numbers are funded first when a member's deduction is partial.")),
                ('assessment_id_FK', models.ForeignKey(db_column='assessment_id_FK', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core_system.monthlyassessment')),
            ],
            options={
                'db_table': 'assessment_items',
                'ordering': ['priority_order', 'item_id_PK'],
            },
        ),
        migrations.CreateModel(
            name='MemberAssessmentAllocation',
            fields=[
                ('allocation_id_PK', models.AutoField(primary_key=True, serialize=False)),
                ('amount_applied', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('amount_remaining', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('assessment_item_id_FK', models.ForeignKey(db_column='assessment_item_id_FK', on_delete=django.db.models.deletion.RESTRICT, related_name='allocations', to='core_system.assessmentitem')),
                ('member_assessment_id_FK', models.ForeignKey(db_column='member_assessment_id_FK', on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='core_system.memberassessment')),
            ],
            options={
                'db_table': 'member_assessment_allocations',
                'ordering': ['assessment_item_id_FK__priority_order', 'allocation_id_PK'],
                'unique_together': {('member_assessment_id_FK', 'assessment_item_id_FK')},
            },
        ),
    ]
