# Generated by Django 5.2.7 on 2026-09-09 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_system', '0123_monthlyassessment_memberassessment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentitem',
            name='custom_label',
            field=models.CharField(blank=True, help_text="Required when purpose is 'other' — the specific purpose name shown to members and reviewers.", max_length=100, null=True),
        ),
    ]
