# Generated by Django 5.2.7 on 2026-09-09 13:15

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_system', '0124_assessmentitem_custom_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberassessment',
            name='prior_month',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='memberassessment',
            name='prior_outstanding',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='memberassessment',
            name='prior_outstanding_collected',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
