# Generated by Django 5.2.7 on 2026-09-09 13:48

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_system', '0125_memberassessment_prior_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberassessment',
            name='change_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='assessmentitem',
            name='custom_label',
            field=models.CharField(blank=True, help_text="Required when purpose is 'other'. For standard purposes, an optional specifier such as the covered period — e.g. two 'Monthly Due' lines distinguished as 'July 2026' and 'August 2026'.", max_length=100, null=True),
        ),
    ]
