# Generated by Django 5.2.16 on 2026-09-10 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_system', '0126_memberassessment_change_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyassessment',
            name='deduction_sheet',
            field=models.FileField(blank=True, help_text='Scanned/source deducted-amount sheet for this month.', null=True, upload_to='assessment_documents/deduction_sheets/'),
        ),
        migrations.AddField(
            model_name='monthlyassessment',
            name='deduction_sheet_uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monthlyassessment',
            name='request_letter',
            field=models.FileField(blank=True, help_text="Scanned ISUCauFA request letter for this month's salary deduction.", null=True, upload_to='assessment_documents/request_letters/'),
        ),
        migrations.AddField(
            model_name='monthlyassessment',
            name='request_letter_uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
