# Generated by Django 5.2.16 on 2026-09-11 01:15
#
# Replaces the single-file attachment fields on MonthlyAssessment with a
# MonthlyAssessmentDocument table so each assessment can carry several
# scanned images per kind (multi-page letters / sheets). Any attachment
# already stored in the old columns is copied into the new table before the
# columns are dropped.

import core_system.models
import django.db.models.deletion
from django.db import migrations, models
from django.utils import timezone


def copy_legacy_attachments(apps, schema_editor):
    MonthlyAssessment = apps.get_model("core_system", "MonthlyAssessment")
    Document = apps.get_model("core_system", "MonthlyAssessmentDocument")
    for assessment in MonthlyAssessment.objects.all().iterator():
        for kind, file_field, ts_field in (
            ("request_letter", "request_letter", "request_letter_uploaded_at"),
            ("deduction_sheet", "deduction_sheet", "deduction_sheet_uploaded_at"),
        ):
            stored = getattr(assessment, file_field)
            if not stored:
                continue
            # Reuse the already-stored file path — no binary copy needed.
            Document.objects.create(
                assessment_id_FK=assessment,
                kind=kind,
                image=stored.name,
                uploaded_at=getattr(assessment, ts_field) or timezone.now(),
            )


class Migration(migrations.Migration):

    dependencies = [
        ('core_system', '0127_monthlyassessment_deduction_sheet_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyAssessmentDocument',
            fields=[
                ('document_id_PK', models.AutoField(primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('request_letter', 'Request Letter'), ('deduction_sheet', 'Deducted Amount Sheet')], max_length=30)),
                ('image', models.FileField(upload_to=core_system.models.assessment_document_upload_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('assessment_id_FK', models.ForeignKey(db_column='assessment_id_FK', on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core_system.monthlyassessment')),
                ('uploaded_by_id_FK', models.ForeignKey(blank=True, db_column='uploaded_by_id_FK', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessment_documents_uploaded', to='core_system.officeruser')),
            ],
            options={
                'db_table': 'monthly_assessment_documents',
                'ordering': ['uploaded_at', 'document_id_PK'],
            },
        ),
        migrations.RunPython(copy_legacy_attachments, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='monthlyassessment',
            name='deduction_sheet',
        ),
        migrations.RemoveField(
            model_name='monthlyassessment',
            name='deduction_sheet_uploaded_at',
        ),
        migrations.RemoveField(
            model_name='monthlyassessment',
            name='request_letter',
        ),
        migrations.RemoveField(
            model_name='monthlyassessment',
            name='request_letter_uploaded_at',
        ),
    ]
