# Generated by Django 5.2.16 on 2026-09-11 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_system', '0128_remove_monthlyassessment_deduction_sheet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyassessment',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_treasurer', 'With Treasurer'), ('pending_audit', 'Pending Auditor Verification'), ('pending_final', 'Pending President Approval'), ('final_approved', 'Final Approved'), ('rejected', 'Rejected by Auditor'), ('returned', 'Returned by President')], default='draft', max_length=50),
        ),
    ]
