# Generated by Django 4.2.30 on 2026-09-16 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_system', '0130_supportingproof_document_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundtransaction',
            name='source_type',
            field=models.CharField(choices=[('payroll_batch', 'Payroll Batch'), ('death_aid', 'Death Aid Disbursement'), ('medical_aid', 'Medical Aid Disbursement'), ('membership_fee', 'Membership Fee'), ('monthly_dues', 'Monthly Dues'), ('contribution', 'Contribution'), ('manual_adjustment', 'Manual Adjustment'), ('aid_post_payment', 'Aid Post Fund Payment'), ('salary_deduction_remittance', 'Salary Deduction Remittance'), ('other_transaction', 'Other Transaction')], max_length=50),
        ),
    ]
