# Generated by Django 4.2.30 on 2026-09-17 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_system', '0132_member_member_classification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='positionrank',
            name='category',
            field=models.CharField(default='Other', max_length=100),
        ),
        migrations.CreateModel(
            name='PositionCategory',
            fields=[
                ('category_id_PK', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by_user_id_FK', models.ForeignKey(blank=True, db_column='created_by_user_id_FK', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core_system.officeruser')),
            ],
            options={
                'db_table': 'position_category',
                'ordering': ['name'],
            },
        ),
    ]
