# Generated by Django 4.2.30 on 2026-09-18 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_system', '0136_member_push_enabled'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='memberassessment',
            index=models.Index(fields=['member_id_FK', 'status', 'assessment_id_FK'], name='member_asse_member__711e24_idx'),
        ),
        migrations.AddIndex(
            model_name='memberledger',
            index=models.Index(fields=['member_id_FK', 'recorded_at', 'ledger_id_PK'], name='member_ledg_member__f9c06a_idx'),
        ),
        migrations.AddIndex(
            model_name='memberledger',
            index=models.Index(fields=['reference_type', 'reference_id'], name='member_ledg_referen_0d5b44_idx'),
        ),
        migrations.AddIndex(
            model_name='monthlyassessment',
            index=models.Index(fields=['status', 'month'], name='monthly_ass_status_390138_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient_type', 'recipient_id', 'sent_at', 'notification_id_PK'], name='notificatio_recipie_9e152a_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient_type', 'recipient_id', 'is_read'], name='notificatio_recipie_e611ec_idx'),
        ),
    ]
