# Generated by Django 5.2.16 on 2026-09-20 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_system', '0138_memberassessment_is_excluded'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='civil_status',
            field=models.CharField(blank=True, choices=[('Single', 'Single'), ('Married', 'Married'), ('Widowed', 'Widowed'), ('Separated', 'Separated'), ('Annulled', 'Annulled')], db_column='civil_status', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='date_of_birth',
            field=models.DateField(blank=True, db_column='date_of_birth', null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='sex',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], db_column='sex', max_length=10, null=True),
        ),
    ]
