# Generated by Django 5.2.17 on 2026-09-23 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_system', '0113_rename_fund_transa_directi_c179cb_idx_fund_transa_directi_6f3d56_idx_and_more'),
        ('core_system', '0139_member_personal_info'),
    ]

    operations = [
    ]
