# Generated by Django 5.2.17 on 2026-09-23 00:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_system', '0140_merge_20260923_0838'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyassessment',
            name='deposit_reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='monthlyassessment',
            name='deposited_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='monthlyassessment',
            name='deposited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monthlyassessment',
            name='deposited_by_id_FK',
            field=models.ForeignKey(blank=True, db_column='deposited_by_id_FK', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monthly_assessments_deposited', to='core_system.officeruser'),
        ),
        migrations.AlterField(
            model_name='memberassessment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Verification'), ('verified', 'Verified by Auditor'), ('approved', 'Approved')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='monthlyassessment',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_treasurer', 'Pending Treasurer Review'), ('pending_deposit', 'Pending Deposit'), ('pending_audit', 'Pending Auditor Verification'), ('pending_final', 'Pending President Approval'), ('final_approved', 'Approved'), ('rejected', 'Rejected by Auditor'), ('returned', 'Returned by President')], default='draft', max_length=50),
        ),
        migrations.AlterField(
            model_name='monthlyassessmentdocument',
            name='kind',
            field=models.CharField(choices=[('request_letter', 'Request Letter'), ('deduction_sheet', 'Deducted Amount Sheet'), ('deposit_slip', 'Deposit Slip')], max_length=30),
        ),
    ]
