# Generated by Django 5.2.17 on 2026-09-23 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_system', '0141_monthlyassessment_deposit_reference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='outgoingemail',
            name='claimed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
