# Generated by Django 5.2.17 on 2026-09-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_system', '0142_outgoingemail_claimed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='dues_backfill_pending',
            field=models.BooleanField(default=False),
        ),
    ]
