# Generated by Django 5.2.17 on 2026-09-24 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_system', '0143_member_dues_backfill_pending'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberassessment',
            name='prior_collected_months',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='memberassessment',
            name='prior_months',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
