# Generated by Django 5.2.17 on 2026-09-25 02:16

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_system', '0144_memberassessment_prior_collected_months_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundtransaction',
            name='source_type',
            field=models.CharField(choices=[('payroll_batch', 'Payroll Batch'), ('death_aid', 'Death Aid Disbursement'), ('medical_aid', 'Medical Aid Disbursement'), ('membership_fee', 'Membership Fee'), ('monthly_dues', 'Monthly Dues'), ('aid_setaside_medical', 'Medical Aid Set-Aside'), ('aid_setaside_death', 'Death Aid Set-Aside'), ('contribution', 'Contribution'), ('manual_adjustment', 'Manual Adjustment'), ('aid_post_payment', 'Aid Post Fund Payment'), ('salary_deduction_remittance', 'Salary Deduction Remittance'), ('other_transaction', 'Other Transaction')], max_length=50),
        ),
        migrations.CreateModel(
            name='AidSetAside',
            fields=[
                ('setaside_id_PK', models.AutoField(primary_key=True, serialize=False)),
                ('aid_type', models.CharField(choices=[('medical_aid', 'Medical Aid'), ('death_aid', 'Death Aid')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('amount_released', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('aid_tracking_post_id_FK', models.ForeignKey(blank=True, db_column='aid_tracking_post_id_FK', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aid_set_asides', to='core_system.aidtrackingpost')),
                ('assessment_item_id_FK', models.ForeignKey(db_column='assessment_item_id_FK', on_delete=django.db.models.deletion.RESTRICT, related_name='set_asides', to='core_system.assessmentitem')),
                ('fund_transaction_id_FK', models.ForeignKey(db_column='fund_transaction_id_FK', on_delete=django.db.models.deletion.CASCADE, related_name='aid_set_asides', to='core_system.fundtransaction')),
                ('member_assessment_id_FK', models.ForeignKey(db_column='member_assessment_id_FK', on_delete=django.db.models.deletion.CASCADE, related_name='aid_set_asides', to='core_system.memberassessment')),
            ],
            options={
                'db_table': 'aid_set_asides',
                'ordering': ['setaside_id_PK'],
                'indexes': [models.Index(fields=['aid_type', 'aid_tracking_post_id_FK'], name='aid_set_asi_aid_typ_26322f_idx')],
                'unique_together': {('member_assessment_id_FK', 'assessment_item_id_FK')},
            },
        ),
    ]
