# Generated by Django 5.2.17 on 2026-09-25 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_system', '0146_align_membership_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationfundreport',
            name='report_type',
            field=models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=20),
        ),
    ]
