# Generated by Django 5.2.17 on 2026-09-25 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_system', '0147_alter_organizationfundreport_report_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentitem',
            name='purpose',
            field=models.CharField(choices=[('monthly_due', 'Monthly Due'), ('medical_aid_fund', 'Medical Aid Fund'), ('death_aid_fund', 'Death Aid Fund'), ('other', 'Other')], max_length=100),
        ),
    ]
