# Generated by Django 5.2.17 on 2026-09-25 22:38

from django.db import migrations, models


def _reclassify_non_teaching(apps, schema_editor):
    """Fold the removed Non-Teaching classification into Teaching.

    Non-teaching staff are not part of this association (they are covered by
    NASA), so the classification no longer exists. Their rows stay in place —
    only the classification changes, and from the next assessment onward they
    are assessed as Teaching members.
    """
    Member = apps.get_model("core_system", "Member")
    Member.objects.filter(member_classification="Non-Teaching").update(
        member_classification="Teaching"
    )


class Migration(migrations.Migration):

    dependencies = [
        ('core_system', '0148_alter_assessmentitem_purpose'),
    ]

    operations = [
        migrations.RunPython(
            _reclassify_non_teaching,
            migrations.RunPython.noop,  # irreversible: the old values are gone
        ),
        migrations.AlterField(
            model_name='member',
            name='member_classification',
            field=models.CharField(choices=[('Teaching', 'Teaching'), ('Retired', 'Retired')], db_column='member_classification', default='Teaching', max_length=20),
        ),
    ]
