# Generated by Django 5.2.17 on 2026-09-26 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_system', '0149_alter_member_member_classification'),
    ]

    operations = [
        migrations.AddField(
            model_name='backupjob',
            name='system_archive_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='backupjob',
            name='backup_type',
            field=models.CharField(choices=[('db', 'Database'), ('media', 'Media'), ('config', 'Config'), ('system', 'System Codebase')], max_length=20),
        ),
    ]
