# Generated by Django 5.2.17 on 2026-09-27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core_system", "0151_seed_academic_ranks"),
    ]

    operations = [
        migrations.CreateModel(
            name="MemberCatchupDue",
            fields=[
                ("catchup_due_id_PK", models.AutoField(primary_key=True, serialize=False)),
                ("month", models.DateField(help_text="First day of the historical month covered by this catch-up due.")),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by_id_FK", models.ForeignKey(blank=True, db_column="created_by_id_FK", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="member_catchup_dues_created", to="core_system.officeruser")),
                ("member_id_FK", models.ForeignKey(db_column="member_id_FK", on_delete=django.db.models.deletion.CASCADE, related_name="catchup_dues", to="core_system.member")),
            ],
            options={
                "db_table": "member_catchup_dues",
                "ordering": ["month", "catchup_due_id_PK"],
                "unique_together": {("member_id_FK", "month")},
            },
        ),
        migrations.AddIndex(
            model_name="membercatchupdue",
            index=models.Index(fields=["member_id_FK", "month"], name="member_cat_member__7a7e8b_idx"),
        ),
    ]
