# Generated by Django 5.2.17 on 2026-09-29 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_system', '0154_external_campus_aid'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='membercatchupdue',
            new_name='member_catc_member__b6ea3f_idx',
            old_name='member_cat_member__7a7e8b_idx',
        ),
        migrations.AlterField(
            model_name='aidtrackingpost',
            name='source_id',
            field=models.IntegerField(blank=True, help_text='PK of the DeathAid/MedicalAid record, or the AssessmentItem for external aid', null=True),
        ),
        migrations.AlterField(
            model_name='aidtrackingpost',
            name='source_type',
            field=models.CharField(blank=True, help_text="'death_aid', 'medical_aid' or 'external_aid' — the aid that triggered this tracking post", max_length=50, null=True),
        ),
    ]
