# Generated by Django 5.2.17 on 2026-09-29 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_system', '0157_assessment_document_hashes'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackForm',
            fields=[
                ('form_id_PK', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('section_title', models.CharField(blank=True, default='', max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('is_open', models.BooleanField(default=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('show_on_roles', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_id_FK', models.ForeignKey(blank=True, db_column='created_by_id_FK', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_forms_created', to='core_system.officeruser')),
            ],
            options={
                'db_table': 'feedback_form',
                'ordering': ['-is_active', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackQuestion',
            fields=[
                ('question_id_PK', models.AutoField(primary_key=True, serialize=False)),
                ('prompt', models.CharField(max_length=400)),
                ('qtype', models.CharField(choices=[('mc', 'Multiple choice'), ('likert', 'Likert scale'), ('text', 'Freeform text')], default='mc', max_length=10)),
                ('options', models.JSONField(blank=True, default=list)),
                ('scale_min', models.PositiveSmallIntegerField(default=1)),
                ('scale_max', models.PositiveSmallIntegerField(default=5)),
                ('min_choices', models.PositiveSmallIntegerField(default=1)),
                ('max_choices', models.PositiveSmallIntegerField(default=1)),
                ('is_required', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('help_text', models.CharField(blank=True, default='', max_length=300)),
                ('form_id_FK', models.ForeignKey(db_column='form_id_FK', on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='core_system.feedbackform')),
            ],
            options={
                'db_table': 'feedback_question',
                'ordering': ['display_order', 'question_id_PK'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackResponse',
            fields=[
                ('response_id_PK', models.AutoField(primary_key=True, serialize=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('device_info', models.CharField(blank=True, default='', max_length=255)),
                ('form_id_FK', models.ForeignKey(db_column='form_id_FK', on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='core_system.feedbackform')),
                ('officer_id_FK', models.ForeignKey(db_column='officer_id_FK', on_delete=django.db.models.deletion.CASCADE, related_name='feedback_responses', to='core_system.officeruser')),
            ],
            options={
                'db_table': 'feedback_response',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackAnswer',
            fields=[
                ('answer_id_PK', models.AutoField(primary_key=True, serialize=False)),
                ('value_text', models.TextField(blank=True, default='')),
                ('value_int', models.IntegerField(blank=True, null=True)),
                ('value_list', models.JSONField(blank=True, default=list)),
                ('question_id_FK', models.ForeignKey(db_column='question_id_FK', on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='core_system.feedbackquestion')),
                ('response_id_FK', models.ForeignKey(db_column='response_id_FK', on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='core_system.feedbackresponse')),
            ],
            options={
                'db_table': 'feedback_answer',
                'ordering': ['question_id_FK__display_order', 'answer_id_PK'],
            },
        ),
        migrations.AddConstraint(
            model_name='feedbackresponse',
            constraint=models.UniqueConstraint(fields=('form_id_FK', 'officer_id_FK'), name='uniq_feedback_response_per_officer'),
        ),
    ]
