# Generated by Django 5.2.17 on 2026-09-29 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_system', '0158_feedback_forms'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedbackanswer',
            options={'ordering': ['answer_id_PK']},
        ),
    ]
