# Generated by Django 5.2.17 on 2026-10-04 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_system', '0161_data_field_encryption'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetLine',
            fields=[
                ('budget_line_id_PK', models.AutoField(primary_key=True, serialize=False)),
                ('fiscal_year', models.IntegerField(help_text='YYYY')),
                ('category', models.CharField(choices=[('monthly_dues', 'Monthly Dues Collections'), ('membership_fee', 'Membership Fees'), ('contributions', 'Contributions'), ('aid_medical', 'Medical Aid Payouts'), ('aid_death', 'Death Aid Payouts'), ('operations', 'Operations & Other Outflows')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'budget_line',
                'ordering': ['fiscal_year', 'category'],
                'constraints': [models.UniqueConstraint(fields=('fiscal_year', 'category'), name='uniq_budget_year_category')],
            },
        ),
    ]
