# Generated by Django 5.2.17 on 2026-10-05 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_system', '0162_budget_line'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='push_enabled',
            field=models.BooleanField(db_column='push_enabled', default=True),
        ),
    ]
