# Generated by Django 5.2.5 on 2026-10-06 14:48

import core_system.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_system', '0163_member_push_mandatory'),
    ]

    operations = [
        migrations.AddField(
            model_name='officeruser',
            name='authenticator_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='officeruser',
            name='authenticator_enrolled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='officeruser',
            name='authenticator_secret',
            field=core_system.fields.EncryptedCharField(blank=True, max_length=500, null=True),
        ),
        migrations.CreateModel(
            name='MfaBackupCode',
            fields=[
                ('code_id_PK', models.AutoField(primary_key=True, serialize=False)),
                ('code_hash', models.CharField(max_length=128)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('officer_id_FK', models.ForeignKey(db_column='officer_id_FK', on_delete=django.db.models.deletion.CASCADE, related_name='mfa_backup_codes', to='core_system.officeruser')),
            ],
            options={
                'db_table': 'mfa_backup_code',
            },
        ),
    ]
