# Generated by Django 5.2.17 on 2026-10-07 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_system', '0165_officeruser_backup_codes_issued_at'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='fundtransaction',
            index=models.Index(fields=['-recorded_at'], name='fund_transa_recorde_cc8f2c_idx'),
        ),
    ]
